export const SOUSUO_VERSION = "0.1.3";
export const SOUSUO_CLIENT_ID = `sousuo/${SOUSUO_VERSION}`;
export const ANYSEARCH_DSH_VERSION = SOUSUO_VERSION;
export const ANYSEARCH_DSH_CLIENT_ID = SOUSUO_CLIENT_ID;
